title: Dimitris Fotis Sakellariou
description: Posts as sanity checks
author: "Dimitris Fotis Sakellariou"

theme: minima
markdown: kramdown
# mathjax: true

base_url: #/gh-pages-minima-starter

# Minima social links
twitter_username: dfsakellariou
github_username: meechos
linkedin_username: sacellarius
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
